// Code generated by mockery v2.45.1. DO NOT EDIT.

package ws

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// MockWebSocket is an autogenerated mock type for the WebSocket type
type MockWebSocket struct {
	mock.Mock
}

// Handle provides a mock function with given fields: c
func (_m *MockWebSocket) Handle(c *gin.Context) {
	_m.Called(c)
}

// HandleOrderUpdates provides a mock function with given fields: c
func (_m *MockWebSocket) HandleOrderUpdates(c *gin.Context) {
	_m.Called(c)
}

// NewMockWebSocket creates a new instance of MockWebSocket. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebSocket(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebSocket {
	mock := &MockWebSocket{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
