// Code generated by mockery v2.45.1. DO NOT EDIT.

package ws

import mock "github.com/stretchr/testify/mock"

// MockHub is an autogenerated mock type for the Hub type
type MockHub struct {
	mock.Mock
}

// BroadcastMessage provides a mock function with given fields: message
func (_m *MockHub) BroadcastMessage(message []byte) {
	_m.Called(message)
}

// Register provides a mock function with given fields: client
func (_m *MockHub) Register(client *Client) {
	_m.Called(client)
}

// Run provides a mock function with given fields:
func (_m *MockHub) Run() {
	_m.Called()
}

// Unregister provides a mock function with given fields: client
func (_m *MockHub) Unregister(client *Client) {
	_m.Called(client)
}

// NewMockHub creates a new instance of MockHub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHub {
	mock := &MockHub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
