// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	OrderItems string
	Orders     string
	Products   string
	Users      string
}{
	OrderItems: "order_items",
	Orders:     "orders",
	Products:   "products",
	Users:      "users",
}
