//go:build !test\n// +build !test

// Code generated by mockery v2.45.1. DO NOT EDIT.

package orm

import mock "github.com/stretchr/testify/mock"

// MockUpsertOptionFunc is an autogenerated mock type for the UpsertOptionFunc type
type MockUpsertOptionFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: o
func (_m *MockUpsertOptionFunc) Execute(o *UpsertOptions) {
	_m.Called(o)
}

// NewMockUpsertOptionFunc creates a new instance of MockUpsertOptionFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpsertOptionFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpsertOptionFunc {
	mock := &MockUpsertOptionFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
